# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  
variables:
  # the name of the service connection that you created above
  serviceConnectionToAzure: 'azureSubscription'
  # the name of your web app here is the same one you used above
  # when you created the web app using the Azure CL
  
resources:
  repositories:	
  - repository: 'template'
    type: github	  # the name of your web app here is the same one you used above
    name: 'hello-project'	  # when you created the web app using the Azure CL
    ref: 'refs/heads/master'	
    endpoint: serviceConnectionToAzure
    
steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    goals: 'package'
    
